"""empty message

Revision ID: 963babb5492c
Revises: 
Create Date: 2023-11-28 10:04:56.500674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963babb5492c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot',
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('token', 'bot_id', name=op.f('pk_bot'))
    )
    op.create_index(op.f('ix_bot_user_id'), 'bot', ['user_id'], unique=False)
    op.create_index(op.f('ix_bot_username'), 'bot', ['username'], unique=False)
    op.create_table('channel',
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('members_count', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', 'bot_id', name=op.f('pk_channel')),
    postgresql_partition_by='LIST (bot_id)'
    )
    op.create_index(op.f('ix_channel_chat_id'), 'channel', ['chat_id'], unique=False)
    op.create_index(op.f('ix_channel_user_id'), 'channel', ['user_id'], unique=False)
    op.create_table('chat',
    sa.Column('is_super_group', sa.Boolean(), nullable=False),
    sa.Column('is_forum', sa.Boolean(), nullable=False),
    sa.Column('members_count', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', 'bot_id', name=op.f('pk_chat')),
    postgresql_partition_by='LIST (bot_id)'
    )
    op.create_index(op.f('ix_chat_chat_id'), 'chat', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_user_id'), 'chat', ['user_id'], unique=False)
    op.create_table('user',
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('last_name', sa.String(length=256), nullable=True),
    sa.Column('language_code', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'bot_id', name=op.f('pk_user')),
    postgresql_partition_by='LIST (bot_id)'
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_chat_user_id'), table_name='chat')
    op.drop_index(op.f('ix_chat_chat_id'), table_name='chat')
    op.drop_table('chat')
    op.drop_index(op.f('ix_channel_user_id'), table_name='channel')
    op.drop_index(op.f('ix_channel_chat_id'), table_name='channel')
    op.drop_table('channel')
    op.drop_index(op.f('ix_bot_username'), table_name='bot')
    op.drop_index(op.f('ix_bot_user_id'), table_name='bot')
    op.drop_table('bot')
    # ### end Alembic commands ###
